import 'dart:convert';

import 'package:http/http.dart' as http;

/// One caption track of a video.
class CaptionTrack {
  final String languageCode;
  final String name;
  final bool isAutoGenerated;
  final bool isTranslatable;
  final String baseUrl;

  const CaptionTrack({
    required this.languageCode,
    required this.name,
    required this.isAutoGenerated,
    required this.isTranslatable,
    required this.baseUrl,
  });
}

/// One caption cue (a line of text at a point in time).
class CaptionCue {
  final int startMs;
  final int durationMs;
  final String text;

  const CaptionCue({
    required this.startMs,
    required this.durationMs,
    required this.text,
  });
}

/// Fetches the caption track list and cues from YouTube's timedtext
/// endpoints — the same ones the web player uses. Also supports
/// server-side translation to any of [supportedLanguages] via the
/// `tlang` parameter.
class CaptionService {
  /// Languages captions can be translated into (timedtext `tlang`).
  static const supportedLanguages = {
    'en': 'English',
    'ru': 'Русский',
    'ky': 'Кыргызча',
    'kk': 'Қазақша',
    'ko': '한국어',
    'zh': '中文',
    'ja': '日本語',
    'uz': 'O‘zbekcha',
    'tg': 'Тоҷикӣ',
    'tr': 'Türkçe',
    'az': 'Azərbaycan',
    'de': 'Deutsch',
    'fr': 'Français',
    'es': 'Español',
    'ar': 'العربية',
    'hi': 'हिन्दी',
  };

  /// UI language codes -> timedtext `tlang` values (ISO codes).
  static const tlangFor = {
    'en': 'en',
    'ru': 'ru',
    'ky': 'ky',
    'kk': 'kk',
    'ko': 'ko',
    'zh': 'zh-Hans',
    'ja': 'ja',
    'uz': 'uz',
    'tg': 'tg',
    'tr': 'tr',
    'az': 'az',
    'de': 'de',
    'fr': 'fr',
    'es': 'es',
    'ar': 'ar',
    'hi': 'hi',
  };

  /// The ANDROID_VR client (keyless InnerTube, verified live).
  static const _vrUa =
      'com.google.android.apps.youtube.vr.oculus/1.65.10 (Linux; U; '
      'Android 12L; eureka-user Build/SQ3A.220605.009.A1) gzip';

  /// Picks the best track for [lang]: an exact non-auto-generated
  /// match first, then an auto-generated match, then any non-auto
  /// track. Null when there are no tracks at all.
  static CaptionTrack? pickTrack(List<CaptionTrack> tracks, String lang) {
    if (tracks.isEmpty) return null;
    CaptionTrack? exact;
    CaptionTrack? exactAuto;
    CaptionTrack? any;
    CaptionTrack? anyAuto;
    for (final t in tracks) {
      if (t.languageCode == lang) {
        if (!t.isAutoGenerated && exact == null) exact = t;
        if (t.isAutoGenerated && exactAuto == null) exactAuto = t;
      }
      if (!t.isAutoGenerated && any == null) any = t;
      if (t.isAutoGenerated && anyAuto == null) anyAuto = t;
    }
    return exact ?? exactAuto ?? any ?? anyAuto;
  }

  /// Fetches the list of caption tracks for [videoId] via the keyless
  /// ANDROID_VR /player call (captions ride the player response —
  /// verified live: this client needs no key, no PO token, no STS).
  static Future<List<CaptionTrack>> fetchTracks(String videoId) async {
    final resp = await http
        .post(
          Uri.parse('https://www.youtube.com/youtubei/v1/player'),
          headers: {
            'Content-Type': 'application/json',
            'User-Agent': _vrUa,
          },
          body: jsonEncode({
            'context': {
              'client': {
                'clientName': 'ANDROID_VR',
                'clientVersion': '1.65.10',
                'hl': 'en',
                'gl': 'US',
                'deviceMake': 'Oculus',
                'deviceModel': 'Quest 3',
                'androidSdkVersion': 32,
                'osName': 'Android',
                'osVersion': '12L',
              },
            },
            'videoId': videoId,
            'contentCheckOk': true,
            'racyCheckOk': true,
          }),
        )
        .timeout(const Duration(seconds: 20));
    if (resp.statusCode != 200) {
      throw Exception('player -> HTTP ${resp.statusCode}');
    }
    final body = jsonDecode(utf8.decode(resp.bodyBytes))
        as Map<String, dynamic>;
    if (body['playabilityStatus']?['status'] != 'OK') {
      throw Exception(
          'playability: ${body['playabilityStatus']?['status']}');
    }
    final list = body['captions']?['playerCaptionsTracklistRenderer']
        ?['captionTracks'] as List?;
    if (list == null) return const [];
    final tracks = <CaptionTrack>[];
    for (final t in list) {
      if (t is! Map) continue;
      final lang = t['languageCode']?.toString() ?? '';
      final base = t['baseUrl']?.toString() ?? '';
      if (lang.isEmpty || base.isEmpty) continue;
      String name = '';
      try {
        final runs = (t['name'] as Map)['runs'] as List;
        if (runs.isNotEmpty && runs.first is Map) {
          name = (runs.first as Map)['text']?.toString() ?? '';
        }
      } catch (_) {}
      tracks.add(CaptionTrack(
        languageCode: lang,
        name: name,
        isAutoGenerated: t['kind']?.toString() == 'asr',
        isTranslatable: t['isTranslatable'] == true,
        baseUrl: base,
      ));
    }
    return tracks;
  }

  /// Fetches the cues of [track], optionally translated into
  /// [translateTo] (a [tlangFor] value). Throws on rate limiting so
  /// callers can surface a friendly message.
  static Future<List<CaptionCue>> fetchCues(
    CaptionTrack track,
    String? translateTo,
  ) async {
    var url = track.baseUrl;
    if (translateTo != null &&
        translateTo.isNotEmpty &&
        translateTo != track.languageCode) {
      url += url.contains('?') ? '&tlang=$translateTo' : '?tlang=$translateTo';
    }
    final resp = await http.get(
      Uri.parse(url),
      headers: {'User-Agent': _vrUa},
    ).timeout(const Duration(seconds: 15));
    if (resp.statusCode == 429) {
      throw Exception('rate-limited');
    }
    if (resp.statusCode != 200) {
      throw Exception('timedtext -> HTTP ${resp.statusCode}');
    }
    return parseCues(utf8.decode(resp.bodyBytes));
  }

  /// Parses timedtext XML. YouTube serves two shapes:
  /// legacy `<text start="" dur="">` and json3-style `<p t="" d="">`.
  static List<CaptionCue> parseCues(String xml) {
    final cues = <CaptionCue>[];

    // Shape 1: <p t="1360" d="1680">line</p>
    // Capture all attributes in one group, then pull t/d out of it —
    // avoids the greedy `[^>]*` swallowing the optional d= match.
    for (final m in RegExp(
      r'<p\b([^>]*)>(.*?)</p>',
      dotAll: true,
    ).allMatches(xml)) {
      final attrs = m.group(1) ?? '';
      final t = RegExp(r'\bt="(\d+)"').firstMatch(attrs)?.group(1);
      if (t == null) continue;
      final d = RegExp(r'\bd="(\d+)"').firstMatch(attrs)?.group(1);
      _add(cues, t, d, m.group(2) ?? '');
    }

    // Shape 2: <text start="1.2" dur="3.4">line</text>
    if (cues.isEmpty) {
      for (final m in RegExp(
        r'<text\b([^>]*)>(.*?)</text>',
        dotAll: true,
      ).allMatches(xml)) {
        final attrs = m.group(1) ?? '';
        final start = RegExp(r'\bstart="([\d.]+)"')
            .firstMatch(attrs)
            ?.group(1);
        if (start == null) continue;
        final dur = RegExp(r'\bdur="([\d.]+)"')
            .firstMatch(attrs)
            ?.group(1);
        final startMs = ((double.tryParse(start) ?? 0) * 1000).round();
        final durMs = ((double.tryParse(dur ?? '0') ?? 0) * 1000).round();
        _add(cues, '$startMs', '$durMs', m.group(2) ?? '');
      }
    }
    return cues;
  }

  static void _add(
      List<CaptionCue> cues, String startMs, String? durMs, String raw) {
    final text = _unescape(raw);
    if (text.isEmpty) return;
    cues.add(CaptionCue(
      startMs: int.tryParse(startMs) ?? 0,
      durationMs: int.tryParse(durMs ?? '0') ?? 0,
      text: text,
    ));
  }

  /// Unescapes the handful of entities YouTube emits and strips tags
  /// the auto-captions leave inline (e.g. `<c>` color runs).
  static String _unescape(String raw) {
    var t = raw
        .replaceAll('&#39;', "'")
        .replaceAll('&quot;', '"')
        .replaceAll('&amp;', '&')
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>');
    t = t.replaceAll(RegExp(r'<[^>]*>'), '');
    t = t.replaceAll(RegExp(r'\s+'), ' ');
    return t.trim();
  }
}
