import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:vidora/state/app_state.dart';

/// Tiny hand-rolled l10n: one class, 9 languages, key lookups with
/// English fallback. No codegen, no intl dependency.
///
/// `S` doubles as the YouTube content-locale selector: [hl] feeds the
/// InnerTube context so titles/view-counts come back localized too.
class S {
  final String code;

  /// InnerTube hl value (YouTube metadata language).
  final String hl;

  const S._(this.code, this.hl);

  static const en = S._('en', 'en');
  static const ru = S._('ru', 'ru');
  static const ky = S._('ky', 'ky');
  static const kk = S._('kk', 'kk');
  static const ko = S._('ko', 'ko');
  static const zh = S._('zh', 'zh-Hans');
  static const ja = S._('ja', 'ja');
  static const uz = S._('uz', 'uz');
  static const tg = S._('tg', 'tg');

  static const all = [en, ru, ky, kk, ko, zh, ja, uz, tg];

  /// UI label of the language in its own tongue.
  static const names = {
    'en': 'English',
    'ru': 'Русский',
    'ky': 'Кыргызча',
    'kk': 'Қазақша',
    'ko': '한국어',
    'zh': '中文',
    'ja': '日本語',
    'uz': 'O‘zbekcha',
    'tg': 'Тоҷикӣ',
  };

  String get label => names[code] ?? code;

  /// Parse a stored code into an [S] (English fallback).
  static S parse(String code) {
    for (final s in all) {
      if (s.code == code) return s;
    }
    return en;
  }

  /// Raw key lookup with English fallback.
  String t(String key) {
    final table = _data[code] ?? _data['en']!;
    return table[key] ?? _data['en']![key] ?? key;
  }

  // ---- generated-style getters (one per key) ----

  String get appTitle => t('app_title');
  String get home => t('home');
  String get search => t('search');
  String get subs => t('subs');
  String get history => t('history');
  String get saved => t('saved');
  String get settings => t('settings');
  String get homeNow => t('cat_now');
  String get homeMusic => t('cat_music');
  String get homeGaming => t('cat_gaming');
  String get homeNews => t('cat_news');
  String get homeTech => t('cat_tech');
  String get homeSports => t('cat_sports');
  String get homeMovies => t('cat_movies');
  String get homeShorts => t('cat_shorts');
  String get loadingShorts => t('loading_shorts');
  String get loadingFeed => t('loading_feed');
  String get nothingHere => t('nothing_here');
  String get retry => t('retry');
  String get searchHint => t('search_hint');
  String get searching => t('searching');
  String get searchHistoryEmpty => t('search_history_empty');
  String get viewsSuffix => t('views_suffix');
  String get likesSuffix => t('likes_suffix');
  String get live => t('live');
  String get watching => t('watching');
  String get resolving => t('resolving_streams');
  String get noStreams => t('no_streams');
  String get subscribe => t('subscribe');
  String get subscribed => t('subscribed');
  String get subscribers => t('subscribers');
  String get save => t('save');
  String get savedLower => t('saved_lower');
  String get bookmark => t('bookmark');
  String get removeBookmark => t('remove_bookmark');
  String get goChannel => t('go_channel');
  String get channel => t('channel');
  String get loadingChannel => t('loading_channel');
  String get videos => t('videos_count');
  String get noVideos => t('no_videos');
  String get findChannel => t('find_channel');
  String get sortNewest => t('sort_newest');
  String get sortPopular => t('sort_popular');
  String get sortOldest => t('sort_oldest');
  String get sortBy => t('sort_by');
  String get titleAZ => t('title_az');
  String get subsEmpty => t('subs_empty');
  String get buildingFeed => t('building_feed');
  String get nothingWatched => t('history_empty');
  String get historyDisabled => t('history_disabled');
  String get watchHistory => t('watch_history');
  String get watchHistorySub => t('history_stored_device');
  String get clearHistoryQ => t('clear_history_q');
  String get clearHistoryBody => t('clear_history_body');
  String get clear => t('clear');
  String get cancel => t('cancel');
  String get bookmarksEmpty => t('bookmarks_empty');
  String get removeAllQ => t('remove_all_q');
  String get bookmarksBody => t('bookmarks_body');
  String get remove => t('remove');
  String get close => t('close');
  String get player => t('player');
  String get defaultQuality => t('default_quality');
  String get highestAvailable => t('highest_available');
  String get autoplayNext => t('autoplay_next');
  String get autoplayNextSub => t('autoplay_next_sub');
  String get privacy => t('privacy');
  String get content => t('content');
  String get contentRegion => t('content_region');
  String get language => t('language');
  String get aboutVidora => t('about_vidora');
  String get aboutText => t('about_text');
  String get version => t('version');
  String get licensedUnder => t('licensed_under');
  String get watchedPct => t('watched_pct');
  String get quality => t('quality');
  String get captions => t('captions');
  String get captionsOff => t('captions_off');
  String get translate => t('translate');
  String get translateOriginal => t('translate_original');
  String get captionsUnavailable => t('captions_unavailable');
  String get translating => t('translating');
  String get captionsRateLimited => t('captions_rate_limited');
}

/// `context.s` — the localized strings for the current UI language.
extension SContext on BuildContext {
  S get s => read<AppState>().lang;
}

const _data = <String, Map<String, String>>{
  'en': {
    'app_title': 'Vidora',
    'home': 'Home',
    'search': 'Search',
    'subs': 'Subs',
    'history': 'History',
    'saved': 'Saved',
    'settings': 'Settings',
    'cat_now': 'Now',
    'cat_music': 'Music',
    'cat_gaming': 'Gaming',
    'cat_news': 'News',
    'cat_tech': 'Tech',
    'cat_sports': 'Sports',
    'cat_movies': 'Movies',
    'loading_shorts': 'Loading shorts…',
    'cat_shorts': 'Shorts',
    'loading_feed': 'Loading feed…',
    'nothing_here': 'Nothing here yet.',
    'retry': 'Retry',
    'search_hint': 'Search videos, shorts, channels…',
    'searching': 'Searching…',
    'search_history_empty':
        'Search for anything on YouTube — anonymously.',
    'views_suffix': 'views',
    'likes_suffix': 'likes',
    'live': 'LIVE',
    'watching': 'Watching',
    'resolving_streams': 'Resolving streams…',
    'no_streams': 'No playable streams found for this video.',
    'subscribe': 'Subscribe',
    'subscribed': 'Subscribed',
    'subscribers': 'subscribers',
    'save': 'Save',
    'saved_lower': 'Saved',
    'bookmark': 'Bookmark',
    'remove_bookmark': 'Remove bookmark',
    'go_channel': 'Go to channel',
    'channel': 'Channel',
    'loading_channel': 'Loading channel…',
    'videos_count': 'videos',
    'no_videos': 'No videos on this channel.',
    'find_channel': 'Find channel',
    'sort_newest': 'Newest',
    'sort_popular': 'Popular',
    'sort_oldest': 'Oldest',
    'sort_by': 'Sort by',
    'title_az': 'Title A–Z',
    'subs_empty':
        'No subscriptions yet. Subscribe to channels from any video or channel page.',
    'building_feed': 'Building your feed…',
    'history_empty': 'Nothing watched yet.',
    'history_disabled': 'Watch history is disabled in Settings.',
    'watch_history': 'Watch history',
    'history_stored_device': 'Stored only on this device',
    'clear_history_q': 'Clear history?',
    'clear_history_body':
        'This removes all watch history from this device.',
    'clear': 'Clear',
    'cancel': 'Cancel',
    'bookmarks_empty':
        'No bookmarks yet. Tap the bookmark icon on any video.',
    'remove_all_q': 'Remove all bookmarks?',
    'bookmarks_body': 'Saved videos will be removed from this device.',
    'remove': 'Remove',
    'close': 'Close',
    'player': 'Player',
    'default_quality': 'Default quality',
    'highest_available': 'Highest available',
    'autoplay_next': 'Autoplay next',
    'autoplay_next_sub': 'Play suggested videos when one ends',
    'privacy': 'Privacy',
    'content': 'Content',
    'content_region': 'Content region',
    'language': 'Language',
    'about_vidora': 'About Vidora',
    'about_text':
        'A privacy-friendly YouTube client built with Flutter and KMEP. '
        'No account, no ads, no tracking — everything runs on your device.',
    'version': 'Version',
    'licensed_under': 'Licensed under GPL-3.0.',
    'watched_pct': '% watched',
    'quality': 'Quality',
    'captions': 'Captions',
    'captions_off': 'Off',
    'translate': 'Translate',
    'translate_original': 'Original',
    'captions_unavailable': 'No captions for this video',
    'translating': 'Translating…',
    'captions_rate_limited':
        'Translation rate-limited, try again shortly.',
  },
  'ru': {
    'app_title': 'Vidora',
    'home': 'Главная',
    'search': 'Поиск',
    'subs': 'Подписки',
    'history': 'История',
    'saved': 'Избранное',
    'settings': 'Настройки',
    'cat_now': 'Сейчас',
    'cat_music': 'Музыка',
    'cat_gaming': 'Игры',
    'cat_news': 'Новости',
    'cat_tech': 'Технологии',
    'cat_sports': 'Спорт',
    'cat_movies': 'Кино',
    'loading_shorts': 'Загрузка shorts…',
    'cat_shorts': 'Shorts',
    'loading_feed': 'Загрузка ленты…',
    'nothing_here': 'Пока ничего нет.',
    'retry': 'Повторить',
    'search_hint': 'Искать видео, шортсы, каналы…',
    'searching': 'Поиск…',
    'search_history_empty': 'Ищите что угодно на YouTube — анонимно.',
    'views_suffix': 'просмотров',
    'likes_suffix': 'лайков',
    'live': 'ПРЯМОЙ ЭФИР',
    'watching': 'Просмотр',
    'resolving_streams': 'Получение потоков…',
    'no_streams': 'Не найдено воспроизводимых потоков для этого видео.',
    'subscribe': 'Подписаться',
    'subscribed': 'Вы подписаны',
    'subscribers': 'подписчиков',
    'save': 'Сохранить',
    'saved_lower': 'Сохранено',
    'bookmark': 'В закладки',
    'remove_bookmark': 'Убрать из закладок',
    'go_channel': 'Перейти к каналу',
    'channel': 'Канал',
    'loading_channel': 'Загрузка канала…',
    'videos_count': 'видео',
    'no_videos': 'На этом канале нет видео.',
    'find_channel': 'Найти канал',
    'sort_newest': 'Новые',
    'sort_popular': 'Популярные',
    'sort_oldest': 'Старые',
    'sort_by': 'Сортировка',
    'title_az': 'Название А–Я',
    'subs_empty':
        'Пока нет подписок. Подпишитесь на каналы со страницы видео или канала.',
    'building_feed': 'Собираем вашу ленту…',
    'history_empty': 'Вы ещё ничего не смотрели.',
    'history_disabled': 'История просмотра отключена в настройках.',
    'watch_history': 'История просмотра',
    'history_stored_device': 'Хранится только на этом устройстве',
    'clear_history_q': 'Очистить историю?',
    'clear_history_body':
        'Вся история просмотра будет удалена с устройства.',
    'clear': 'Очистить',
    'cancel': 'Отмена',
    'bookmarks_empty': 'Пока нет закладок. Нажмите значок закладки на видео.',
    'remove_all_q': 'Удалить все закладки?',
    'bookmarks_body': 'Сохранённые видео будут удалены с устройства.',
    'remove': 'Удалить',
    'close': 'Закрыть',
    'player': 'Плеер',
    'default_quality': 'Качество по умолчанию',
    'highest_available': 'Максимальное доступное',
    'autoplay_next': 'Автовоспроизведение',
    'autoplay_next_sub': 'Воспроизводить похожие видео после текущего',
    'privacy': 'Приватность',
    'content': 'Контент',
    'content_region': 'Регион контента',
    'language': 'Язык',
    'about_vidora': 'О приложении',
    'about_text':
        'Приватный YouTube-клиент на Flutter и KMEP. Без аккаунта, '
        'рекламы и слежки — всё работает на вашем устройстве.',
    'version': 'Версия',
    'licensed_under': 'Лицензия GPL-3.0.',
    'watched_pct': '% просмотрено',
    'quality': 'Качество',
    'captions': 'Субтитры',
    'captions_off': 'Выкл.',
    'translate': 'Перевод',
    'translate_original': 'Оригинал',
    'captions_unavailable': 'Для этого видео нет субтитров',
    'translating': 'Перевод…',
    'captions_rate_limited': 'Перевод ограничен, попробуйте позже.',
  },
  'ky': {
    'app_title': 'Vidora',
    'home': 'Башкы бет',
    'search': 'Издөө',
    'subs': 'Жазылуулар',
    'history': 'Тарых',
    'saved': 'Сакталгандар',
    'settings': 'Жөндөөлөр',
    'cat_now': 'Азыркы',
    'cat_music': 'Музыка',
    'cat_gaming': 'Оюндар',
    'cat_news': 'Жаңылыктар',
    'cat_tech': 'Технология',
    'cat_sports': 'Спорт',
    'cat_movies': 'Кино',
    'loading_shorts': 'Shorts жүктөлүп жатат…',
    'cat_shorts': 'Shorts',
    'loading_feed': 'Тизме жүктөлүп жатат…',
    'nothing_here': 'Азырынча эч нерсе жок.',
    'retry': 'Кайра аракет кыл',
    'search_hint': 'Видео, шортс, каналдарды издөө…',
    'searching': 'Изделип жатат…',
    'search_history_empty': 'YouTube’до каалаган нерсени издөө — анонимдүү.',
    'views_suffix': 'көрүү',
    'likes_suffix': 'жактыруу',
    'live': 'ТИКЕЙ ЭФИР',
    'watching': 'Көрүү',
    'resolving_streams': 'Агымдар алынууда…',
    'no_streams': 'Бул видеодо ойнотууга боло турган агым табылбады.',
    'subscribe': 'Жазылуу',
    'subscribed': 'Жазылдыңыз',
    'subscribers': 'жазылуучу',
    'save': 'Сакта',
    'saved_lower': 'Сакталды',
    'bookmark': 'Белгилөө',
    'remove_bookmark': 'Белгини алып сал',
    'go_channel': 'Каналга өтүү',
    'channel': 'Канал',
    'loading_channel': 'Канал жүктөлүп жатат…',
    'videos_count': 'видео',
    'no_videos': 'Бул каналда видео жок.',
    'find_channel': 'Каналды тап',
    'sort_newest': 'Жаңы',
    'sort_popular': 'Популярдуу',
    'sort_oldest': 'Эски',
    'sort_by': 'Ирээттөө',
    'title_az': 'Аталыш А–Я',
    'subs_empty':
        'Азырынча жазылуу жок. Видеолордон же каналдардан жазылыңыз.',
    'building_feed': 'Тизмеңиз түзүлүп жатат…',
    'history_empty': 'Азырынча эч нерсе көрүлгөн жок.',
    'history_disabled': 'Көрүү тарыхы жөндөөлөрдө өчүрүлгөн.',
    'watch_history': 'Көрүү тарыхы',
    'history_stored_device': 'Тек гана бул устройстводо сакталат',
    'clear_history_q': 'Тарыхты тазалоо?',
    'clear_history_body': 'Көрүү тарыхы түгөл устройстводон өчүрүлөт.',
    'clear': 'Тазалоо',
    'cancel': 'Жокко чыгаруу',
    'bookmarks_empty':
        'Азырынча белги жок. Видеодогу белги белгисин басыңыз.',
    'remove_all_q': 'Бардык белгилерди өчүрөсүзбү?',
    'bookmarks_body': 'Сакталган видеолор устройстводон өчүрүлөт.',
    'remove': 'Өчүрүү',
    'close': 'Жабуу',
    'player': 'Плеер',
    'default_quality': 'Демейки сапат',
    'highest_available': 'Эң жогорку сапат',
    'autoplay_next': 'Автоойнотуу',
    'autoplay_next_sub': 'Бир видео бүткөндө кийинкисин ойнотуу',
    'privacy': 'Купуялык',
    'content': 'Мазмун',
    'content_region': 'Мазмун региону',
    'language': 'Тил',
    'about_vidora': 'Тиркеме жөнүндө',
    'about_text':
        'Flutter жана KMEP менен курулган купуялыкты сактаган YouTube-клиент. '
        'Эсеп жок, реклама жок, көзөмөл жок — баары түзүлүшүңүздө иштейт.',
    'version': 'Версия',
    'licensed_under': 'GPL-3.0 лицензиясы.',
    'watched_pct': '% көрүлдү',
    'quality': 'Сапат',
    'captions': 'Субтитрлер',
    'captions_off': 'Өчүрүлгөн',
    'translate': 'Котормо',
    'translate_original': 'Түп нуска',
    'captions_unavailable': 'Бул видеодо субтитр жок',
    'translating': 'Котормо жүрүп жатат…',
    'captions_rate_limited': 'Котормо чектелген, кийинчерээк аракет кылыңыз.',
  },
  'kk': {
    'app_title': 'Vidora',
    'home': 'Басты бет',
    'search': 'Іздеу',
    'subs': 'Жазылулар',
    'history': 'Тарих',
    'saved': 'Сақталғандар',
    'settings': 'Параметрлер',
    'cat_now': 'Қазір',
    'cat_music': 'Музыка',
    'cat_gaming': 'Ойындар',
    'cat_news': 'Жаңалықтар',
    'cat_tech': 'Технология',
    'cat_sports': 'Спорт',
    'cat_movies': 'Кино',
    'loading_shorts': 'Shorts жүктелуде…',
    'cat_shorts': 'Shorts',
    'loading_feed': 'Тізім жүктелуде…',
    'nothing_here': 'Әзірге ештеңе жоқ.',
    'retry': 'Қайта тырыс',
    'search_hint': 'Видео, шортс, арналар іздеу…',
    'searching': 'Ізделуде…',
    'search_history_empty': 'YouTube’да кез келген нәрсені іздеу — анонимді.',
    'views_suffix': 'қарау',
    'likes_suffix': 'ұнасы',
    'live': 'ТІКЕЛІ ЭФІР',
    'watching': 'Көру',
    'resolving_streams': 'Ағындар алынуда…',
    'no_streams': 'Бұл видеода ойнатуға болатын ағын табылмады.',
    'subscribe': 'Жазылу',
    'subscribed': 'Жазылдыңыз',
    'subscribers': 'жазылушы',
    'save': 'Сақтау',
    'saved_lower': 'Сақталды',
    'bookmark': 'Белгілеу',
    'remove_bookmark': 'Белгіні алып тастау',
    'go_channel': 'Арнаға өту',
    'channel': 'Арна',
    'loading_channel': 'Арна жүктелуде…',
    'videos_count': 'видео',
    'no_videos': 'Бұл арнада видео жоқ.',
    'find_channel': 'Арна табу',
    'sort_newest': 'Жаңа',
    'sort_popular': 'Танымал',
    'sort_oldest': 'Ескі',
    'sort_by': 'Сұрыптау',
    'title_az': 'Атауы А–Я',
    'subs_empty':
        'Әзірге жазылу жоқ. Видеолардан немесе арналардан жазылыңыз.',
    'building_feed': 'Тізіміңіз құрылуда…',
    'history_empty': 'Әзірге ештеңе көрмедіңіз.',
    'history_disabled': 'Көру тарихы параметрлерде өшірілген.',
    'watch_history': 'Көру тарихы',
    'history_stored_device': 'Тек осы құрылғыда сақталады',
    'clear_history_q': 'Тарихты тазалау керек пе?',
    'clear_history_body': 'Көру тарихы құрылғыдан толық өшіріледі.',
    'clear': 'Тазалау',
    'cancel': 'Болдырмау',
    'bookmarks_empty': 'Әзірге белгі жоқ. Видеодағы белгі белгісін басыңыз.',
    'remove_all_q': 'Барлық белгілерді өшіресіз бе?',
    'bookmarks_body': 'Сақталған видеолар құрылғыдан өшіріледі.',
    'remove': 'Өшіру',
    'close': 'Жабу',
    'player': 'Плеер',
    'default_quality': 'Әдепкі сапа',
    'highest_available': 'Ең жоғары сапа',
    'autoplay_next': 'Автоойнату',
    'autoplay_next_sub': 'Бір видео аяқталғанда келесісін ойнату',
    'privacy': 'Құпиялық',
    'content': 'Контент',
    'content_region': 'Контент өңірі',
    'language': 'Тіл',
    'about_vidora': 'Қосымша туралы',
    'about_text':
        'Flutter және KMEP арқылы жасалған құпиялықты сақтайтын YouTube-клиент. '
        'Есеп жоқ, жарнама жоқ, бақылау жоқ — бәрі құрылғыңызда жұмыс істейді.',
    'version': 'Нұсқа',
    'licensed_under': 'GPL-3.0 лицензиясы.',
    'watched_pct': '% көрілді',
    'quality': 'Сапа',
    'captions': 'Субтитрлер',
    'captions_off': 'Өшірулі',
    'translate': 'Аударма',
    'translate_original': 'Түпнұсқа',
    'captions_unavailable': 'Бұл видеода субтитр жоқ',
    'translating': 'Аударылуда…',
    'captions_rate_limited': 'Аударма шектеулі, кейінірек тырысыңыз.',
  },
  'ko': {
    'app_title': 'Vidora',
    'home': '홈',
    'search': '검색',
    'subs': '구독',
    'history': '시청 기록',
    'saved': '저장됨',
    'settings': '설정',
    'cat_now': '지금',
    'cat_music': '음악',
    'cat_gaming': '게임',
    'cat_news': '뉴스',
    'cat_tech': '테크',
    'cat_sports': '스포츠',
    'cat_movies': '영화',
    'loading_shorts': 'Shorts 불러오는 중…',
    'cat_shorts': 'Shorts',
    'loading_feed': '피드 불러오는 중…',
    'nothing_here': '아직 아무것도 없습니다.',
    'retry': '재시도',
    'search_hint': '동영상, 쇼츠, 채널 검색…',
    'searching': '검색 중…',
    'search_history_empty': 'YouTube에서 무엇이든 검색하세요 — 익명으로.',
    'views_suffix': '회',
    'likes_suffix': '좋아요',
    'live': '라이브',
    'watching': '시청 중',
    'resolving_streams': '스트림 확인 중…',
    'no_streams': '이 동영상의 재생 가능한 스트림이 없습니다.',
    'subscribe': '구독',
    'subscribed': '구독함',
    'subscribers': '명 구독자',
    'save': '저장',
    'saved_lower': '저장됨',
    'bookmark': '북마크',
    'remove_bookmark': '북마크 제거',
    'go_channel': '채널로 이동',
    'channel': '채널',
    'loading_channel': '채널 불러오는 중…',
    'videos_count': '개 동영상',
    'no_videos': '이 채널에는 동영상이 없습니다.',
    'find_channel': '채널 찾기',
    'sort_newest': '최신',
    'sort_popular': '인기',
    'sort_oldest': '오래된',
    'sort_by': '정렬 기준',
    'title_az': '제목 A–Z',
    'subs_empty': '아직 구독이 없습니다. 동영상이나 채널 페이지에서 구독하세요.',
    'building_feed': '피드 생성 중…',
    'history_empty': '아직 시청한 것이 없습니다.',
    'history_disabled': '시청 기록이 설정에서 꺼져 있습니다.',
    'watch_history': '시청 기록',
    'history_stored_device': '이 기기에만 저장됩니다',
    'clear_history_q': '기록을 지우시겠습니까?',
    'clear_history_body': '이 기기의 모든 시청 기록이 삭제됩니다.',
    'clear': '지우기',
    'cancel': '취소',
    'bookmarks_empty': '아직 북마크가 없습니다. 동영상의 북마크 아이콘을 누르세요.',
    'remove_all_q': '모든 북마크를 제거할까요?',
    'bookmarks_body': '저장된 동영상이 이 기기에서 제거됩니다.',
    'remove': '제거',
    'close': '닫기',
    'player': '플레이어',
    'default_quality': '기본 화질',
    'highest_available': '사용 가능한 최고 화질',
    'autoplay_next': '자동 재생',
    'autoplay_next_sub': '동영상이 끝나면 다음 동영상 재생',
    'privacy': '개인정보',
    'content': '콘텐츠',
    'content_region': '콘텐츠 지역',
    'language': '언어',
    'about_vidora': '정보',
    'about_text':
        'Flutter와 KMEP로 만든 개인정보 보호 YouTube 클라이언트. '
        '계정도, 광고도, 추적도 없습니다 — 모든 것이 기기에서 실행됩니다.',
    'version': '버전',
    'licensed_under': 'GPL-3.0 라이선스.',
    'watched_pct': '% 시청함',
    'quality': '화질',
    'captions': '자막',
    'captions_off': '끔',
    'translate': '번역',
    'translate_original': '원문',
    'captions_unavailable': '이 동영상에는 자막이 없습니다',
    'translating': '번역 중…',
    'captions_rate_limited': '번역이 제한되었습니다. 잠시 후 다시 시도하세요.',
  },
  'zh': {
    'app_title': 'Vidora',
    'home': '首页',
    'search': '搜索',
    'subs': '订阅',
    'history': '历史',
    'saved': '收藏',
    'settings': '设置',
    'cat_now': '当前',
    'cat_music': '音乐',
    'cat_gaming': '游戏',
    'cat_news': '新闻',
    'cat_tech': '科技',
    'cat_sports': '体育',
    'cat_movies': '电影',
    'loading_shorts': '正在加载短片…',
    'cat_shorts': '短片',
    'loading_feed': '正在加载内容…',
    'nothing_here': '这里还没有内容。',
    'retry': '重试',
    'search_hint': '搜索视频、短片、频道…',
    'searching': '搜索中…',
    'search_history_empty': '匿名搜索 YouTube 上的一切。',
    'views_suffix': '次观看',
    'likes_suffix': '赞',
    'live': '直播',
    'watching': '正在观看',
    'resolving_streams': '正在获取视频流…',
    'no_streams': '未找到此视频的可播放流。',
    'subscribe': '订阅',
    'subscribed': '已订阅',
    'subscribers': '位订阅者',
    'save': '保存',
    'saved_lower': '已保存',
    'bookmark': '收藏',
    'remove_bookmark': '取消收藏',
    'go_channel': '转到频道',
    'channel': '频道',
    'loading_channel': '正在加载频道…',
    'videos_count': '个视频',
    'no_videos': '此频道没有视频。',
    'find_channel': '查找频道',
    'sort_newest': '最新',
    'sort_popular': '热门',
    'sort_oldest': '最早',
    'sort_by': '排序方式',
    'title_az': '标题 A–Z',
    'subs_empty': '还没有订阅。请在视频或频道页面订阅。',
    'building_feed': '正在生成你的内容流…',
    'history_empty': '还没有观看记录。',
    'history_disabled': '观看历史已在设置中关闭。',
    'watch_history': '观看历史',
    'history_stored_device': '仅存储在此设备上',
    'clear_history_q': '清除历史记录？',
    'clear_history_body': '将删除此设备上的所有观看历史。',
    'clear': '清除',
    'cancel': '取消',
    'bookmarks_empty': '还没有收藏。点击视频上的收藏图标。',
    'remove_all_q': '删除所有收藏？',
    'bookmarks_body': '保存的视频将从设备中删除。',
    'remove': '删除',
    'close': '关闭',
    'player': '播放器',
    'default_quality': '默认画质',
    'highest_available': '最高可用画质',
    'autoplay_next': '自动连播',
    'autoplay_next_sub': '当前视频结束后播放推荐视频',
    'privacy': '隐私',
    'content': '内容',
    'content_region': '内容地区',
    'language': '语言',
    'about_vidora': '关于',
    'about_text':
        '基于 Flutter 和 KMEP 构建的隐私友好 YouTube 客户端。'
        '无账号、无广告、无追踪 — 一切都在设备上运行。',
    'version': '版本',
    'licensed_under': 'GPL-3.0 许可证。',
    'watched_pct': '% 已观看',
    'quality': '画质',
    'captions': '字幕',
    'captions_off': '关闭',
    'translate': '翻译',
    'translate_original': '原文',
    'captions_unavailable': '此视频没有字幕',
    'translating': '翻译中…',
    'captions_rate_limited': '翻译受限，请稍后再试。',
  },
  'ja': {
    'app_title': 'Vidora',
    'home': 'ホーム',
    'search': '検索',
    'subs': '登録チャンネル',
    'history': '履歴',
    'saved': '保存',
    'settings': '設定',
    'cat_now': '今',
    'cat_music': '音楽',
    'cat_gaming': 'ゲーム',
    'cat_news': 'ニュース',
    'cat_tech': 'テック',
    'cat_sports': 'スポーツ',
    'cat_movies': '映画',
    'loading_shorts': 'ショートを読み込み中…',
    'cat_shorts': 'ショート',
    'loading_feed': 'フィードを読み込み中…',
    'nothing_here': 'まだ何もありません。',
    'retry': '再試行',
    'search_hint': '動画、ショート、チャンネルを検索…',
    'searching': '検索中…',
    'search_history_empty': 'YouTube を匿名で自由に検索できます。',
    'views_suffix': '回視聴',
    'likes_suffix': '高評価',
    'live': 'ライブ',
    'watching': '視聴中',
    'resolving_streams': 'ストリームを解決中…',
    'no_streams': 'この動画の再生可能なストリームが見つかりません。',
    'subscribe': '登録',
    'subscribed': '登録済み',
    'subscribers': '人の登録者',
    'save': '保存',
    'saved_lower': '保存済み',
    'bookmark': 'ブックマーク',
    'remove_bookmark': 'ブックマークを削除',
    'go_channel': 'チャンネルへ移動',
    'channel': 'チャンネル',
    'loading_channel': 'チャンネルを読み込み中…',
    'videos_count': '本の動画',
    'no_videos': 'このチャンネルには動画がありません。',
    'find_channel': 'チャンネルを探す',
    'sort_newest': '新着',
    'sort_popular': '人気',
    'sort_oldest': '古い順',
    'sort_by': '並べ替え',
    'title_az': 'タイトル A–Z',
    'subs_empty': 'まだ登録がありません。動画やチャンネルページから登録してください。',
    'building_feed': 'フィードを生成中…',
    'history_empty': 'まだ何も視聴していません。',
    'history_disabled': '視聴履歴は設定で無効になっています。',
    'watch_history': '視聴履歴',
    'history_stored_device': 'この端末にのみ保存されます',
    'clear_history_q': '履歴を消去しますか？',
    'clear_history_body': 'この端末のすべての視聴履歴が削除されます。',
    'clear': '消去',
    'cancel': 'キャンセル',
    'bookmarks_empty':
        'まだブックマークがありません。動画のブックマークアイコンをタップしてください。',
    'remove_all_q': 'すべてのブックマークを削除しますか？',
    'bookmarks_body': '保存した動画がこの端末から削除されます。',
    'remove': '削除',
    'close': '閉じる',
    'player': 'プレーヤー',
    'default_quality': 'デフォルト画質',
    'highest_available': '最高画質',
    'autoplay_next': '自動再生',
    'autoplay_next_sub': '動画の終了時に次の動画を再生',
    'privacy': 'プライバシー',
    'content': 'コンテンツ',
    'content_region': 'コンテンツ地域',
    'language': '言語',
    'about_vidora': 'このアプリについて',
    'about_text':
        'Flutter と KMEP で作られたプライバシー重視の YouTube クライアント。'
        'アカウント不要、広告なし、追跡なし — すべて端末上で動作します。',
    'version': 'バージョン',
    'licensed_under': 'GPL-3.0 ライセンス。',
    'watched_pct': '% 視聴済み',
    'quality': '画質',
    'captions': '字幕',
    'captions_off': 'オフ',
    'translate': '翻訳',
    'translate_original': '原文',
    'captions_unavailable': 'この動画には字幕がありません',
    'translating': '翻訳中…',
    'captions_rate_limited':
        '翻訳が制限されています。しばらくしてから再試行してください。',
  },
  'uz': {
    'app_title': 'Vidora',
    'home': 'Bosh sahifa',
    'search': 'Qidirish',
    'subs': 'Obunalar',
    'history': 'Tarix',
    'saved': 'Saqlanganlar',
    'settings': 'Sozlamalar',
    'cat_now': 'Hozir',
    'cat_music': 'Musiqa',
    'cat_gaming': 'O‘yinlar',
    'cat_news': 'Yangiliklar',
    'cat_tech': 'Texnologiya',
    'cat_sports': 'Sport',
    'cat_movies': 'Kino',
    'loading_shorts': 'Shorts yuklanmoqda…',
    'cat_shorts': 'Shorts',
    'loading_feed': 'Tasma yuklanmoqda…',
    'nothing_here': 'Hozircha hech narsa yo‘q.',
    'retry': 'Qayta urinish',
    'search_hint': 'Videolar, shortslar, kanallar qidirish…',
    'searching': 'Qidirilmoqda…',
    'search_history_empty': 'YouTube’da istalgan narsani qidirish — anonim ravishda.',
    'views_suffix': 'marta',
    'likes_suffix': 'layk',
    'live': 'JONLI',
    'watching': 'Ko‘rish',
    'resolving_streams': 'Oqimlar olinmoqda…',
    'no_streams': 'Bu video uchun ijro mumkin bo‘lgan oqim topilmadi.',
    'subscribe': 'Obuna bo‘lish',
    'subscribed': 'Obuna bo‘ldingiz',
    'subscribers': 'obunachi',
    'save': 'Saqlash',
    'saved_lower': 'Saqlandi',
    'bookmark': 'Belgilash',
    'remove_bookmark': 'Belgini olib tashlash',
    'go_channel': 'Kanalga o‘tish',
    'channel': 'Kanal',
    'loading_channel': 'Kanal yuklanmoqda…',
    'videos_count': 'video',
    'no_videos': 'Bu kanalda video yo‘q.',
    'find_channel': 'Kanal topish',
    'sort_newest': 'Yangi',
    'sort_popular': 'Mashhur',
    'sort_oldest': 'Eski',
    'sort_by': 'Saralash',
    'title_az': 'Nomi A–Z',
    'subs_empty':
        'Hozircha obuna yo‘q. Videolar yoki kanallar sahifasidan obuna bo‘ling.',
    'building_feed': 'Tasmangiz shakllanmoqda…',
    'history_empty': 'Hozircha hech narsa ko‘rmadingiz.',
    'history_disabled': 'Ko‘rish tarixi sozlamalarda o‘chirilgan.',
    'watch_history': 'Ko‘rish tarixi',
    'history_stored_device': 'Faqat shu qurilmada saqlanadi',
    'clear_history_q': 'Tarixni tozalashmi?',
    'clear_history_body': 'Barcha ko‘rish tarixi qurilmadan o‘chiriladi.',
    'clear': 'Tozalash',
    'cancel': 'Bekor qilish',
    'bookmarks_empty': 'Hozircha belgi yo‘q. Videodagi belgi tugmasini bosing.',
    'remove_all_q': 'Barcha belgilar o‘chirilsinmi?',
    'bookmarks_body': 'Saqlangan videolar qurilmadan o‘chiriladi.',
    'remove': 'O‘chirish',
    'close': 'Yopish',
    'player': 'Pleyer',
    'default_quality': 'Standart sifat',
    'highest_available': 'Eng yuqori sifat',
    'autoplay_next': 'Avtomatik ijro',
    'autoplay_next_sub': 'Video tugagach keyingisini ijro etish',
    'privacy': 'Maxfiylik',
    'content': 'Kontent',
    'content_region': 'Kontent hududi',
    'language': 'Til',
    'about_vidora': 'Ilova haqida',
    'about_text':
        'Flutter va KMEP bilan qurilgan maxfiylikka yo‘naltirilgan YouTube '
        'klienti. Hisob yo‘q, reklama yo‘q, kuzatuv yo‘q — hammasi '
        'qurilmangizda ishlaydi.',
    'version': 'Versiya',
    'licensed_under': 'GPL-3.0 litsenziyasi.',
    'watched_pct': '% ko‘rildi',
    'quality': 'Sifat',
    'captions': 'Subtitrlar',
    'captions_off': 'O‘chirilgan',
    'translate': 'Tarjima',
    'translate_original': 'Asl nusxa',
    'captions_unavailable': 'Bu videoda subtitr yo‘q',
    'translating': 'Tarjima qilinmoqda…',
    'captions_rate_limited':
        'Tarjima cheklangan, birozdan so‘ng qayta urinib ko‘ring.',
  },
  'tg': {
    'app_title': 'Vidora',
    'home': 'Асосӣ',
    'search': 'Ҷустуҷӯ',
    'subs': 'Обунаҳо',
    'history': 'Таърих',
    'saved': 'Нигоҳдоштаҳо',
    'settings': 'Танзимот',
    'cat_now': 'Ҳозир',
    'cat_music': 'Мусиқӣ',
    'cat_gaming': 'Бозиҳо',
    'cat_news': 'Хабарҳо',
    'cat_tech': 'Технология',
    'cat_sports': 'Варзиш',
    'cat_movies': 'Кино',
    'loading_shorts': 'Shorts бор мешавад…',
    'cat_shorts': 'Shorts',
    'loading_feed': 'Рӯйхат бор мешавад…',
    'nothing_here': 'Ҳоло ҳеҷ чиз нест.',
    'retry': 'Аз нав кӯшиш',
    'search_hint': 'Видеоҳо, шортсҳо, каналҳоро ҷустуҷӯ кунед…',
    'searching': 'Ҷустуҷӯ равон…',
    'search_history_empty': 'Дар YouTube ҳар чизро ҷустуҷӯ кунед — ношиноса.',
    'views_suffix': 'бinosи',
    'likes_suffix': 'писанд',
    'live': 'МУСТАҚИМ',
    'watching': 'Тамошо',
    'resolving_streams': 'Ҷараёнҳо гирифта мешаванд…',
    'no_streams': 'Барои ин видео ҷараёни бозигарданда ёфт нашуд.',
    'subscribe': 'Обуна шудан',
    'subscribed': 'Обуна шудед',
    'subscribers': 'обунабин',
    'save': 'Нигоҳ доштан',
    'saved_lower': 'Нигоҳ дошта шуд',
    'bookmark': 'Аломат гузоштан',
    'remove_bookmark': 'Аломатро нест кардан',
    'go_channel': 'Ба канал гузаштан',
    'channel': 'Канал',
    'loading_channel': 'Канал бор мешавад…',
    'videos_count': 'видео',
    'no_videos': 'Дар ин канал видео нест.',
    'find_channel': 'Канал ёфтан',
    'sort_newest': 'Нав',
    'sort_popular': 'Маъмул',
    'sort_oldest': 'Кӯҳна',
    'sort_by': 'Ҷудокунӣ',
    'title_az': 'Унвон А–Я',
    'subs_empty': 'Ҳоло обуна нест. Аз саҳифаи видео ё канал обуна шавед.',
    'building_feed': 'Рӯйхати шумо сохта мешавад…',
    'history_empty': 'Ҳоло ҳеҷ чиз тамошо накардаед.',
    'history_disabled': 'Таърихи тамошо дар танзимот хомӯш аст.',
    'watch_history': 'Таърихи тамошо',
    'history_stored_device': 'Танҳо дар ҳамин дастгоҳ нигоҳ дошта мешавад',
    'clear_history_q': 'Таърихро тоза мекунед?',
    'clear_history_body': 'Ҳамаи таърихи тамошо аз дастгоҳ нест карда мешавад.',
    'clear': 'Тоза кардан',
    'cancel': 'Бекор',
    'bookmarks_empty': 'Ҳоло аломат нест. Тугмаи аломатро дар видео пахш кунед.',
    'remove_all_q': 'Ҳамаи аломатҳоро нест мекунед?',
    'bookmarks_body': 'Видеоҳои нигоҳдошта аз дастгоҳ нест мешаванд.',
    'remove': 'Нест кардан',
    'close': 'Пӯшидан',
    'player': 'Плеер',
    'default_quality': 'Сифати пешфарз',
    'highest_available': 'Баландтарин сифат',
    'autoplay_next': 'Худбозӣ',
    'autoplay_next_sub': 'Баъди видео навбатиро бозӣ кардан',
    'privacy': 'Махфият',
    'content': 'Мӯҳтаво',
    'content_region': 'Минтақаи мӯҳтаво',
    'language': 'Забон',
    'about_vidora': 'Дар бораи барнома',
    'about_text':
        'Клиенти YouTube бо Flutter ва KMEP сохта шудааст. '
        'Бе ҳисоб, бе реклама, бе назорат — ҳама чиз дар дастгоҳи шумо кор мекунад.',
    'version': 'Версия',
    'licensed_under': 'Иҷозатномаи GPL-3.0.',
    'watched_pct': '% тамошо шуд',
    'quality': 'Сифат',
    'captions': 'Зертитрҳо',
    'captions_off': 'Хомӯш',
    'translate': 'Тарҷума',
    'translate_original': 'Матн аслӣ',
    'captions_unavailable': 'Барои ин видео зертитр нест',
    'translating': 'Тарҷума мешавад…',
    'captions_rate_limited': 'Тарҷума маҳдуд аст, баъдтар аз нав кӯшиш кунед.',
  },
};
